app:
  cors:
    allowedOrigins:
      - https://localhost:8080
  jwt:
    keystore-path: ../jwt/keystore.jks
    keystore-password: password
    key-alias: oauthkey
    private-key-passphrase: password
  pbkdf2:
    pbkdf2-secret: long_and_secure_string
    salt-length: 1024
    iteration: 64
  otp:
    secret: 3132333435363738393031323334353637383930

spring:
  config:
    import: optional:secrets.yml

server:
  ssl:
    key-store: file:../ssl/keystore/user.p12
    key-store-password: password
    key-password: password
    trustStore: file:../ssl/truststore.p12
    trustStorePassword: password

eureka:
  instance:
    hostname: localhost
  client:
    enabled: false
    serviceUrl:
      defaultZone: https://localhost:8082/eureka
